import { Geist, Geist_Mono, Noto_Sans } from "next/font/google";
import "./globals.css";
import "./animation.css"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const notoSans = Noto_Sans({
  subsets: ['latin'],
  weight: ['400','600', '700'], 
  display: 'swap',
  variable: '--font-noto',
}); 

export const metadata = {
  title: "TherapyPoint",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className = {notoSans.className}>
      <body
      className="vsc-initialized"
      >
        {children}
      </body>
    </html>
  );
}
